trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli@13.3.0
    npm install --legacy-peer-deps
  displayName: 'Installation Angular Dependences'

- script: |
    ng build
  displayName: 'Angular Building'
