trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli@13.3.0
    npm install --legacy-peer-deps
  displayName: 'Installation of Angular Dependences'

- script: |
    npm install -g @aws-amplify/cli
  displayName: 'Install AWS Amplify'

- script: |
    aws configure set aws_access_key_id AKIAQTSUQSAVVU4WSHEX --profile default
    aws configure set aws_secret_access_key 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 --profile default
    aws configure set region us-east-1
  displayName: 'Configure AWS Amplify'

- script: |
    ng build
  displayName: 'Angular Building'

- script: |
    amplify publish --yes --appId d1caevemxf1drz --envName develop
  displayName: 'Publishing'
