trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install --legacy-peer-deps
    npm install -g @aws-amplify/cli
    ng build
  displayName: 'npm install and build'
