trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli@13.3.0
    npm install --legacy-peer-deps
  displayName: 'Installation of Angular Dependences'

- script: |
    npm install -g @aws-amplify/cli
  displayName: 'Install AWS Amplify'

- script: |
    amplify pull --yes --appId d1caevemxf1drz --envName develop
    amplify push --yes
  displayName: 'Configure AWS Amplify'

- script: |
    ng build
  displayName: 'Angular Building'

- script: |
    amplify push
  displayName: 'Publishing'
