export const environment = {
  production: false,
  availableLanguages: ['es', 'en'],
  defaultLanguage: 'es',
  country: {
    code: 'CO',
  },
  //api: 'https://zsso8qc51f.execute-api.us-east-1.amazonaws.com/qa',
  //api: 'https://cuwma9g3ad.execute-api.us-east-1.amazonaws.com/dev',
  api: 'https://ozujxe4oc5.execute-api.us-east-1.amazonaws.com/prod',
  //apiAdmin: 'https://irq3zx9zg2.execute-api.us-east-1.amazonaws.com/qa',
  //apiAdmin: 'https://ve6g2uvg4c.execute-api.us-east-1.amazonaws.com/dev',
  apiAdmin: 'https://7p680oe6na.execute-api.us-east-1.amazonaws.com/prod',
  //apiGetRquests: 'https://bcqylrpd5m.execute-api.us-east-1.amazonaws.com/dev/getRequests',
  //apiAndicom: 'https://andicom.analyzerinc.com/api/',
  apiAndicom: 'https://51hdafc2kk.execute-api.us-east-1.amazonaws.com/dev',
  amplify: {
    auth: {
      mandatorySignIn: true,
      region: 'us-east-1',
      userPoolId: 'us-east-1_SimgfaLBd',
      userPoolWebClientId: '56oibqn2pvgroqnrm5i38a6dvp',
      authenticationFlowType: 'USER_PASSWORD_AUTH',
      oauth: {
        domain: 'dev-users-analyzer-pro.auth.us-east-1.amazoncognito.com',
        scope: ['email', 'openid', 'profile', 'aws.cognito.signin.user.admin'],
        redirectSignIn: 'http://localhost:4200/load-session',
        redirectSignOut: 'http://localhost:4200/',
        responseType: 'code',
      },
      federationTarget: 'COGNITO_USER_POOLS',
      aws_cognito_username_attributes: ['EMAIL'],
      aws_cognito_social_providers: [],
      aws_cognito_signup_attributes: ['EMAIL'],
      aws_cognito_mfa_configuration: 'OFF',
      aws_cognito_mfa_types: ['SMS'],
      aws_cognito_password_protection_settings: {
        passwordPolicyMinLength: 8,
        passwordPolicyCharacters: [],
      },
      aws_cognito_verification_mechanisms: ['EMAIL'],
    },
  },
  security: {
    passwordMinLength: 8,
    randomNameLength: 32,
    verificationCodeLength: 6,
  },
  socket: {
    interval: 10000,
    timeOut: 180000,
  },
  //socketApi: 'wss://3f575jrnag.execute-api.us-east-1.amazonaws.com/dev',
  //socketApi: 'wss://zzpxgnp8ii.execute-api.us-east-1.amazonaws.com/dev',
  socketApi: 'wss://375tfziudk.execute-api.us-east-1.amazonaws.com/prod',
  andinacom: {
    subscription_id: '2bc0d507-6990-4658-a6e1-ceeb4b6e9a76',
    packages: '2',
    userCognito: 'sergio.galvis@itsense.com.co',
    passwsordCgonito: 'Qwerty123**',
    defaultCountry: 'CO',
  },
  amplifyAndicom: {
    auth: {
      mandatorySignIn: true,
      region: 'us-east-1',
      userPoolId: 'us-east-1_jAIudOyp6',
      userPoolWebClientId: '4mj6fgg2ifquh9tbf3k3b17l4t',
      authenticationFlowType: 'USER_PASSWORD_AUTH',
      oauth: {
        domain: 'analyzer-andicom-sept.auth.us-east-1.amazoncognito.com',
        scope: ['email', 'openid', 'profile', 'aws.cognito.signin.user.admin'],
        redirectSignIn: 'http://localhost:4200/load-session',
        redirectSignOut: 'http://localhost:4200/',
        responseType: 'code',
      },
      federationTarget: 'COGNITO_USER_POOLS',
      aws_cognito_username_attributes: ['EMAIL'],
      aws_cognito_social_providers: [],
      aws_cognito_signup_attributes: ['EMAIL'],
      aws_cognito_mfa_configuration: 'OFF',
      aws_cognito_mfa_types: ['SMS'],
      aws_cognito_password_protection_settings: {
        passwordPolicyMinLength: 8,
        passwordPolicyCharacters: [],
      },
      aws_cognito_verification_mechanisms: ['EMAIL'],
    },
  },
  webSiteUrl: 'https://marketing.itsense.com.co/analyzer',
  cryptToken: 'S9h#u3U2&bHDEgD7wSJV2iREc9YR4Pn',
  loadMassiveTemplateFilename: 'load_massive_template_{country}.csv',
};
