export enum Routes {
  HOME = '/',
  LOGIN = '/login',
  DASHBOARD = '/dashboard',
  GENERATE_REPORT = '/dashboard/generate-report',
  GENERATE_MASSIVE_REPORT = '/dashboard/generate-massive-report',
  GENERATE_REPORT_RESULT = '/dashboard/generate-report/generate-report-result',
  SINGLE_QUERY = '/product-admin/single-query',
  SINGLE_QUERY_PACKAGES = '/product-admin/massive-query',
  MASSIVE_QUERY = '/product-admin/massive-query',
  SELECT_PLAN = '/product-admin/select-plan',
  CLIENTS = '/backoffice/clients',
  CREATE_CLIENT = '/backoffice/clients/create-client',
  USERS = '/backoffice/users',
  CREATE_USER = '/backoffice/users/create-user',
  PRODUCTS = '/backoffice/products',
  PLANS = '/backoffice/plans',
  MASSIVE_REPORT_DETAIL = '/dashboard/massive-query-detail',
}
